const WORDS = [
  // ── Greetings (15) ──
  { emoji: "👋", en: "hello / goodbye",              th: "sawadee",                  script: "สวัสดี",                    cat: "greetings" },
  { emoji: "🙏", en: "thank you",                    th: "khob khun",                script: "ขอบคุณ",                    cat: "greetings" },
  { emoji: "😌", en: "you're welcome / no problem",  th: "mai pen rai",              script: "ไม่เป็นไร",                  cat: "greetings" },
  { emoji: "🙇", en: "sorry / excuse me",            th: "kho thot",                 script: "ขอโทษ",                     cat: "greetings" },
  { emoji: "✅", en: "yes",                          th: "chai",                     script: "ใช่",                       cat: "greetings", note: "also used as a polite confirmation particle" },
  { emoji: "❌", en: "no",                           th: "mai chai",                 script: "ไม่ใช่",                    cat: "greetings", note: "mai = negation prefix; mai chai = 'not yes'" },
  { emoji: "🙏", en: "please",                       th: "garuuna",                  script: "กรุณา",                     cat: "greetings" },
  { emoji: "🤔", en: "how are you?",                 th: "sabai dee mai",            script: "สบายดีไหม",                  cat: "greetings" },
  { emoji: "😊", en: "I'm fine",                     th: "sabai dee",                script: "สบายดี",                    cat: "greetings" },
  { emoji: "🤝", en: "nice to meet you",             th: "yin dee tee dai roo jak",  script: "ยินดีที่ได้รู้จัก",            cat: "greetings" },
  { emoji: "🍀", en: "good luck",                    th: "chok dee",                 script: "โชคดี",                     cat: "greetings" },
  { emoji: "🥂", en: "cheers!",                      th: "chon gaew",                script: "ชนแก้ว",                    cat: "greetings" },
  { emoji: "👋", en: "see you later",                th: "laew phob gan mai",        script: "แล้วพบกันใหม่",               cat: "greetings" },
  { emoji: "🌙", en: "good night",                   th: "ratree sawat",             script: "ราตรีสวัสดิ์",                cat: "greetings" },
  { emoji: "😕", en: "I don't understand",           th: "mai khao jai",             script: "ไม่เข้าใจ",                  cat: "greetings" },

  // ── Numbers (25) ──
  { emoji: "0️⃣", en: "zero",                         th: "soon",                     script: "ศูนย์",                     cat: "numbers", num: "0" },
  { emoji: "1️⃣", en: "one",                          th: "neung",                    script: "หนึ่ง",                     cat: "numbers", num: "1" },
  { emoji: "2️⃣", en: "two",                          th: "song",                     script: "สอง",                       cat: "numbers", num: "2" },
  { emoji: "3️⃣", en: "three",                        th: "sam",                      script: "สาม",                       cat: "numbers", num: "3" },
  { emoji: "4️⃣", en: "four",                         th: "see",                      script: "สี่",                       cat: "numbers", num: "4" },
  { emoji: "5️⃣", en: "five",                         th: "ha",                       script: "ห้า",                       cat: "numbers", num: "5" },
  { emoji: "6️⃣", en: "six",                          th: "hok",                      script: "หก",                        cat: "numbers", num: "6" },
  { emoji: "7️⃣", en: "seven",                        th: "jet",                      script: "เจ็ด",                      cat: "numbers", num: "7" },
  { emoji: "8️⃣", en: "eight",                        th: "paet",                     script: "แปด",                       cat: "numbers", num: "8" },
  { emoji: "9️⃣", en: "nine",                         th: "gao",                      script: "เก้า",                      cat: "numbers", num: "9" },
  { emoji: "🔟", en: "ten",                          th: "sip",                      script: "สิบ",                       cat: "numbers", num: "10" },
  { emoji: "🔢", en: "eleven",                       th: "sip-et",                   script: "สิบเอ็ด",                   cat: "numbers", num: "11" },
  { emoji: "🔢", en: "twelve",                       th: "sip-song",                 script: "สิบสอง",                    cat: "numbers", num: "12" },
  { emoji: "🔢", en: "fifteen",                      th: "sip-ha",                   script: "สิบห้า",                    cat: "numbers", num: "15" },
  { emoji: "🔢", en: "twenty",                       th: "yee-sip",                  script: "ยี่สิบ",                    cat: "numbers", num: "20" },
  { emoji: "🔢", en: "twenty-one",                   th: "yee-sip-et",               script: "ยี่สิบเอ็ด",                 cat: "numbers", num: "21" },
  { emoji: "🔢", en: "thirty",                       th: "sam-sip",                  script: "สามสิบ",                    cat: "numbers", num: "30" },
  { emoji: "🔢", en: "forty",                        th: "see-sip",                  script: "สี่สิบ",                    cat: "numbers", num: "40" },
  { emoji: "🔢", en: "fifty",                        th: "ha-sip",                   script: "ห้าสิบ",                    cat: "numbers", num: "50" },
  { emoji: "💯", en: "one hundred",                  th: "roi",                      script: "ร้อย",                      cat: "numbers", num: "100" },
  { emoji: "🔢", en: "two hundred",                  th: "song roi",                 script: "สองร้อย",                   cat: "numbers", num: "200" },
  { emoji: "🔢", en: "one thousand",                 th: "phan",                     script: "พัน",                       cat: "numbers", num: "1,000" },
  { emoji: "🔢", en: "ten thousand",                 th: "meun",                     script: "หมื่น",                     cat: "numbers", num: "10,000" },
  { emoji: "🔢", en: "one hundred thousand",         th: "saen",                     script: "แสน",                       cat: "numbers", num: "100,000" },
  { emoji: "🔢", en: "one million",                  th: "lan",                      script: "ล้าน",                      cat: "numbers", num: "1,000,000" },

  // ── Colors (12) ──
  { emoji: "🔴", en: "red",                          th: "sii daeng",                script: "สีแดง",                     cat: "colors" },
  { emoji: "🔵", en: "blue",                         th: "sii fah",                  script: "สีฟ้า",                     cat: "colors" },
  { emoji: "🟢", en: "green",                        th: "sii khiao",                script: "สีเขียว",                   cat: "colors" },
  { emoji: "🟡", en: "yellow",                       th: "sii leuang",               script: "สีเหลือง",                  cat: "colors" },
  { emoji: "⚫", en: "black",                        th: "sii dam",                  script: "สีดำ",                      cat: "colors" },
  { emoji: "⚪", en: "white",                        th: "sii khao",                 script: "สีขาว",                     cat: "colors" },
  { emoji: "🩷", en: "pink",                         th: "sii chompoo",              script: "สีชมพู",                    cat: "colors" },
  { emoji: "🟠", en: "orange",                       th: "sii som",                  script: "สีส้ม",                     cat: "colors" },
  { emoji: "🟣", en: "purple",                       th: "sii muang",                script: "สีม่วง",                    cat: "colors" },
  { emoji: "🟤", en: "brown",                        th: "sii nam tan",              script: "สีน้ำตาล",                  cat: "colors" },
  { emoji: "🩶", en: "grey",                         th: "sii thao",                 script: "สีเทา",                     cat: "colors" },
  { emoji: "🥇", en: "gold",                         th: "sii thong",                script: "สีทอง",                     cat: "colors" },

  // ── Food (55) ──
  { emoji: "😋", en: "delicious",                    th: "aroy",                     script: "อร่อย",                     cat: "food" },
  { emoji: "🌶️", en: "spicy",                        th: "pet",                      script: "เผ็ด",                      cat: "food", note: "same romanization as 'duck' (pet) — tone differs" },
  { emoji: "🚫", en: "not spicy",                    th: "mai pet",                  script: "ไม่เผ็ด",                   cat: "food" },
  { emoji: "🍬", en: "sweet",                        th: "wan",                      script: "หวาน",                      cat: "food" },
  { emoji: "🍋", en: "sour",                         th: "priao",                    script: "เปรี้ยว",                   cat: "food" },
  { emoji: "🧂", en: "salty",                        th: "khem",                     script: "เค็ม",                      cat: "food" },
  { emoji: "☕", en: "bitter",                       th: "khom",                     script: "ขม",                        cat: "food" },
  { emoji: "🍚", en: "rice",                         th: "khao",                     script: "ข้าว",                      cat: "food", note: "also: white (color), enter (verb) — tones differ" },
  { emoji: "🍙", en: "sticky rice",                  th: "khao niao",                script: "ข้าวเหนียว",                 cat: "food" },
  { emoji: "🍳", en: "fried rice",                   th: "khao pad",                 script: "ข้าวผัด",                   cat: "food" },
  { emoji: "🍜", en: "noodles",                      th: "gway teow",                script: "ก๋วยเตี๋ยว",                 cat: "food" },
  { emoji: "🍜", en: "pad thai",                     th: "pad thai",                 script: "ผัดไทย",                    cat: "food" },
  { emoji: "🍲", en: "tom yum soup",                 th: "tom yum",                  script: "ต้มยำ",                     cat: "food" },
  { emoji: "🍛", en: "green curry",                  th: "gaeng khiao wan",          script: "แกงเขียวหวาน",               cat: "food" },
  { emoji: "🍛", en: "red curry",                    th: "gaeng daeng",              script: "แกงแดง",                    cat: "food" },
  { emoji: "🥗", en: "papaya salad",                 th: "som tam",                  script: "ส้มตำ",                     cat: "food" },
  { emoji: "🥭", en: "mango sticky rice",            th: "khao niao mamuang",        script: "ข้าวเหนียวมะม่วง",            cat: "food" },
  { emoji: "🥢", en: "spring rolls",                 th: "poh pia",                  script: "ปอเปี๊ยะ",                  cat: "food" },
  { emoji: "🍢", en: "satay",                        th: "satay",                    script: "สะเต๊ะ",                    cat: "food" },
  { emoji: "🍗", en: "chicken",                      th: "gai",                      script: "ไก่",                       cat: "food" },
  { emoji: "🥩", en: "pork",                         th: "moo",                      script: "หมู",                       cat: "food" },
  { emoji: "🥩", en: "beef",                         th: "nuea",                     script: "เนื้อ",                     cat: "food" },
  { emoji: "🐟", en: "fish",                         th: "pla",                      script: "ปลา",                       cat: "food" },
  { emoji: "🦐", en: "shrimp",                       th: "goong",                    script: "กุ้ง",                      cat: "food" },
  { emoji: "🦀", en: "crab",                         th: "poo",                      script: "ปู",                        cat: "food" },
  { emoji: "🦑", en: "squid",                        th: "pla muek",                 script: "ปลาหมึก",                   cat: "food" },
  { emoji: "🥚", en: "egg",                          th: "khai",                     script: "ไข่",                       cat: "food" },
  { emoji: "🧆", en: "tofu",                         th: "tao hoo",                  script: "เต้าหู้",                   cat: "food" },
  { emoji: "🥦", en: "vegetables",                   th: "phak",                     script: "ผัก",                       cat: "food" },
  { emoji: "🧄", en: "garlic",                       th: "gratiam",                  script: "กระเทียม",                  cat: "food" },
  { emoji: "🧅", en: "onion",                        th: "hua hom",                  script: "หัวหอม",                    cat: "food" },
  { emoji: "🌶️", en: "chili",                        th: "phrik",                    script: "พริก",                      cat: "food" },
  { emoji: "🫚", en: "ginger",                       th: "khing",                    script: "ขิง",                       cat: "food" },
  { emoji: "🌿", en: "lemongrass",                   th: "ta krai",                  script: "ตะไคร้",                    cat: "food" },
  { emoji: "🥥", en: "coconut milk",                 th: "ga ti",                    script: "กะทิ",                      cat: "food" },
  { emoji: "🐟", en: "fish sauce",                   th: "nam pla",                  script: "น้ำปลา",                    cat: "food" },
  { emoji: "🫙", en: "soy sauce",                    th: "see-ew",                   script: "ซีอิ๊ว",                    cat: "food" },
  { emoji: "🍬", en: "sugar",                        th: "nam tan",                  script: "น้ำตาล",                    cat: "food", note: "literally 'palm water'; nam tan also = brown (sii nam tan)" },
  { emoji: "🧂", en: "salt",                         th: "gleua",                    script: "เกลือ",                     cat: "food" },
  { emoji: "🍋", en: "lime",                         th: "manao",                    script: "มะนาว",                     cat: "food" },
  { emoji: "🥭", en: "mango",                        th: "mamuang",                  script: "มะม่วง",                    cat: "food" },
  { emoji: "🍌", en: "banana",                       th: "gluai",                    script: "กล้วย",                     cat: "food" },
  { emoji: "🍍", en: "pineapple",                    th: "sapparot",                 script: "สับปะรด",                   cat: "food" },
  { emoji: "🍉", en: "watermelon",                   th: "taeng mo",                 script: "แตงโม",                     cat: "food" },
  { emoji: "🌵", en: "durian",                       th: "thurian",                  script: "ทุเรียน",                   cat: "food" },
  { emoji: "🥥", en: "coconut",                      th: "maprao",                   script: "มะพร้าว",                   cat: "food" },
  { emoji: "🍞", en: "bread",                        th: "khanom pang",              script: "ขนมปัง",                    cat: "food" },
  { emoji: "🍲", en: "soup",                         th: "gaeng / tom",              script: "แกง / ต้ม",                 cat: "food" },
  { emoji: "🥘", en: "stir-fried",                   th: "pad",                      script: "ผัด",                       cat: "food", note: "cooking method prefix, e.g. pad thai, pad kra pao" },
  { emoji: "🍟", en: "deep-fried",                   th: "thot",                     script: "ทอด",                       cat: "food" },
  { emoji: "♨️", en: "steamed",                      th: "neung",                    script: "นึ่ง",                      cat: "food", note: "same romanization as 'one' (neung) — tone differs" },
  { emoji: "🔥", en: "grilled",                      th: "ping / yang",              script: "ปิ้ง / ย่าง",               cat: "food" },
  { emoji: "🍳", en: "fried egg",                    th: "khai dao",                 script: "ไข่ดาว",                    cat: "food" },
  { emoji: "🥚", en: "omelette",                     th: "khai jeow",                script: "ไข่เจียว",                  cat: "food" },
  { emoji: "🍈", en: "papaya",                       th: "malakaw",                  script: "มะละกอ",                    cat: "food" },

  // ── Drinks (10) ──
  { emoji: "💧", en: "water",                        th: "nam",                      script: "น้ำ",                       cat: "drinks" },
  { emoji: "☕", en: "coffee",                       th: "gafae",                    script: "กาแฟ",                      cat: "drinks" },
  { emoji: "🍵", en: "tea",                          th: "cha",                      script: "ชา",                        cat: "drinks" },
  { emoji: "🍺", en: "beer",                         th: "bia",                      script: "เบียร์",                    cat: "drinks" },
  { emoji: "🍷", en: "wine",                         th: "wayn",                     script: "ไวน์",                      cat: "drinks" },
  { emoji: "🧃", en: "juice",                        th: "nam phon lamai",           script: "น้ำผลไม้",                  cat: "drinks" },
  { emoji: "🥥", en: "coconut water",                th: "nam maprao",               script: "น้ำมะพร้าว",                 cat: "drinks" },
  { emoji: "🥤", en: "soda",                         th: "nam at lom",               script: "น้ำอัดลม",                  cat: "drinks" },
  { emoji: "🥛", en: "milk",                         th: "nom",                      script: "นม",                        cat: "drinks" },
  { emoji: "🧊", en: "ice",                          th: "nam khaeng",               script: "น้ำแข็ง",                   cat: "drinks" },

  // ── Family (15) ──
  { emoji: "👨", en: "father",                       th: "pho",                      script: "พ่อ",                       cat: "family" },
  { emoji: "👩", en: "mother",                       th: "mae",                      script: "แม่",                       cat: "family" },
  { emoji: "🧑", en: "older sibling",                th: "phi",                      script: "พี่",                       cat: "family" },
  { emoji: "👶", en: "younger sibling",              th: "nong",                     script: "น้อง",                      cat: "family" },
  { emoji: "💍", en: "husband",                      th: "pua",                      script: "ผัว",                       cat: "family" },
  { emoji: "👰", en: "wife",                         th: "mia",                      script: "เมีย",                      cat: "family" },
  { emoji: "👦", en: "son",                          th: "luk chai",                 script: "ลูกชาย",                    cat: "family" },
  { emoji: "👧", en: "daughter",                     th: "luk sao",                  script: "ลูกสาว",                    cat: "family" },
  { emoji: "👴", en: "grandfather",                  th: "poo / ta",                 script: "ปู่ / ตา",                  cat: "family" },
  { emoji: "👵", en: "grandmother",                  th: "ya / yai",                 script: "ย่า / ยาย",                 cat: "family" },
  { emoji: "👨‍👩‍👧", en: "uncle",                        th: "lung / na",                script: "ลุง / น้า",                 cat: "family" },
  { emoji: "👩‍👩‍👧", en: "aunt",                         th: "pa / na",                  script: "ป้า / น้า",                 cat: "family" },
  { emoji: "🤝", en: "friend",                       th: "pheuan",                   script: "เพื่อน",                    cat: "family" },
  { emoji: "🏘️", en: "neighbor",                     th: "pheuan ban",               script: "เพื่อนบ้าน",                 cat: "family" },
  { emoji: "🧒", en: "child",                        th: "dek / luk",                script: "เด็ก / ลูก",                cat: "family" },

  // ── Body (20) ──
  { emoji: "🗣️", en: "head",                         th: "hua",                      script: "หัว",                       cat: "body" },
  { emoji: "😊", en: "face",                         th: "na",                       script: "หน้า",                      cat: "body" },
  { emoji: "👁️", en: "eye",                          th: "ta",                       script: "ตา",                        cat: "body" },
  { emoji: "👂", en: "ear",                          th: "hoo",                      script: "หู",                        cat: "body" },
  { emoji: "👃", en: "nose",                         th: "jamook",                   script: "จมูก",                      cat: "body" },
  { emoji: "👄", en: "mouth",                        th: "pak",                      script: "ปาก",                       cat: "body" },
  { emoji: "🦷", en: "tooth",                        th: "fan",                      script: "ฟัน",                       cat: "body" },
  { emoji: "💇", en: "hair",                         th: "phom",                     script: "ผม",                        cat: "body" },
  { emoji: "🦒", en: "neck",                         th: "kor",                      script: "คอ",                        cat: "body" },
  { emoji: "💪", en: "shoulder",                     th: "lai",                      script: "ไหล่",                      cat: "body" },
  { emoji: "💪", en: "arm",                          th: "khaen",                    script: "แขน",                       cat: "body" },
  { emoji: "🖐️", en: "hand",                         th: "meu",                      script: "มือ",                       cat: "body" },
  { emoji: "☝️", en: "finger",                       th: "niu",                      script: "นิ้ว",                      cat: "body" },
  { emoji: "🫀", en: "chest",                        th: "ok",                       script: "อก",                        cat: "body" },
  { emoji: "🫃", en: "stomach",                      th: "thong",                    script: "ท้อง",                      cat: "body" },
  { emoji: "🔙", en: "back",                         th: "lang",                     script: "หลัง",                      cat: "body" },
  { emoji: "🦵", en: "leg",                          th: "kha",                      script: "ขา",                        cat: "body" },
  { emoji: "🦵", en: "knee",                         th: "hua khao",                 script: "หัวเข่า",                   cat: "body" },
  { emoji: "🦶", en: "foot",                         th: "tao",                      script: "เท้า",                      cat: "body" },
  { emoji: "❤️", en: "heart",                        th: "hua jai",                  script: "หัวใจ",                     cat: "body" },

  // ── Clothing (15) ──
  { emoji: "👕", en: "shirt",                        th: "seua",                     script: "เสื้อ",                     cat: "clothing" },
  { emoji: "👖", en: "trousers / pants",             th: "gang-geng",                script: "กางเกง",                    cat: "clothing" },
  { emoji: "👗", en: "dress",                        th: "seua phah",                script: "เสื้อผ้า",                  cat: "clothing" },
  { emoji: "👗", en: "skirt",                        th: "gra-prong",                script: "กระโปรง",                   cat: "clothing" },
  { emoji: "👟", en: "shoes",                        th: "rong thao",                script: "รองเท้า",                   cat: "clothing" },
  { emoji: "🩴", en: "sandals",                      th: "rong thao taem",           script: "รองเท้าแตะ",                 cat: "clothing" },
  { emoji: "🧢", en: "hat",                          th: "muat",                     script: "หมวก",                      cat: "clothing" },
  { emoji: "👓", en: "glasses",                      th: "waen ta",                  script: "แว่นตา",                    cat: "clothing" },
  { emoji: "👜", en: "bag",                          th: "gra-pao",                  script: "กระเป๋า",                   cat: "clothing" },
  { emoji: "⌚", en: "watch",                        th: "na li ga",                 script: "นาฬิกา",                    cat: "clothing" },
  { emoji: "💍", en: "ring",                         th: "waen",                     script: "แหวน",                      cat: "clothing" },
  { emoji: "📿", en: "necklace",                     th: "soy kor",                  script: "สร้อยคอ",                   cat: "clothing" },
  { emoji: "👕", en: "clothes",                      th: "seua pha",                 script: "เสื้อผ้า",                  cat: "clothing" },
  { emoji: "🧥", en: "jacket / coat",                th: "seua klum",                script: "เสื้อคลุม",                  cat: "clothing" },
  { emoji: "🩲", en: "underwear",                    th: "gang-geng nai",            script: "กางเกงใน",                  cat: "clothing" },

  // ── Animals (20) ──
  { emoji: "🐕", en: "dog",                          th: "maa (falling tone)",       script: "หมา",                       cat: "animals", note: "falling tone; same syllable as horse (rising) and come (mid)" },
  { emoji: "🐈", en: "cat",                          th: "maew",                     script: "แมว",                       cat: "animals" },
  { emoji: "🐘", en: "elephant",                     th: "chang",                    script: "ช้าง",                      cat: "animals", note: "classifier for elephants; chang also means 'carpenter'" },
  { emoji: "🐒", en: "monkey",                       th: "ling",                     script: "ลิง",                       cat: "animals" },
  { emoji: "🐦", en: "bird",                         th: "nok",                      script: "นก",                        cat: "animals", note: "classifier for birds; also means 'outside' in some contexts" },
  { emoji: "🐍", en: "snake",                        th: "ngu",                      script: "งู",                        cat: "animals" },
  { emoji: "🐯", en: "tiger",                        th: "seua",                     script: "เสือ",                      cat: "animals", note: "same romanization as shirt (seua) — tones differ" },
  { emoji: "🐎", en: "horse",                        th: "maa (rising tone)",        script: "ม้า",                       cat: "animals", note: "rising tone; same syllable as dog (falling) and come (mid)" },
  { emoji: "🐄", en: "cow",                          th: "wua",                      script: "วัว",                       cat: "animals", note: "classifier for cattle" },
  { emoji: "🐷", en: "pig",                          th: "moo",                      script: "หมู",                       cat: "animals", note: "also means pork (food); same word" },
  { emoji: "🦆", en: "duck",                         th: "pet",                      script: "เป็ด",                      cat: "animals", note: "same romanization as spicy (pet) — tones differ" },
  { emoji: "🐰", en: "rabbit",                       th: "gra-tai",                  script: "กระต่าย",                   cat: "animals" },
  { emoji: "🐸", en: "frog",                         th: "gob",                      script: "กบ",                        cat: "animals" },
  { emoji: "🦟", en: "mosquito",                     th: "yung",                     script: "ยุง",                       cat: "animals" },
  { emoji: "🐜", en: "ant",                          th: "mot",                      script: "มด",                        cat: "animals" },
  { emoji: "🦋", en: "butterfly",                    th: "phi seua",                 script: "ผีเสื้อ",                   cat: "animals" },
  { emoji: "🐊", en: "crocodile",                    th: "jaw-ra-khe",               script: "จระเข้",                    cat: "animals" },
  { emoji: "🐟", en: "fish",                         th: "pla",                      script: "ปลา",                       cat: "animals", note: "same word as fish (food)" },
  { emoji: "🐔", en: "chicken (animal)",             th: "gai",                      script: "ไก่",                       cat: "animals", note: "same word as chicken (food); also classifier for chickens" },
  { emoji: "🐃", en: "buffalo",                      th: "khwai",                    script: "ควาย",                      cat: "animals" },

  // ── Nature (15) ──
  { emoji: "☀️", en: "sun",                          th: "pra-a-tit",                script: "พระอาทิตย์",                 cat: "nature" },
  { emoji: "🌙", en: "moon",                         th: "pra-jan",                  script: "พระจันทร์",                  cat: "nature" },
  { emoji: "⭐", en: "star",                         th: "dao",                      script: "ดาว",                       cat: "nature" },
  { emoji: "🌤️", en: "sky",                          th: "fa",                       script: "ฟ้า",                       cat: "nature" },
  { emoji: "☁️", en: "cloud",                        th: "mek",                      script: "เมฆ",                       cat: "nature" },
  { emoji: "🌧️", en: "rain",                         th: "fon",                      script: "ฝน",                        cat: "nature" },
  { emoji: "💨", en: "wind",                         th: "lom",                      script: "ลม",                        cat: "nature" },
  { emoji: "⛰️", en: "mountain",                     th: "phu-khao",                 script: "ภูเขา",                     cat: "nature" },
  { emoji: "🏞️", en: "river",                        th: "mae-nam",                  script: "แม่น้ำ",                    cat: "nature" },
  { emoji: "🌊", en: "sea / ocean",                  th: "ta-le",                    script: "ทะเล",                      cat: "nature" },
  { emoji: "🏖️", en: "beach",                        th: "hat",                      script: "หาด",                       cat: "nature" },
  { emoji: "🏝️", en: "island",                       th: "ko",                       script: "เกาะ",                      cat: "nature" },
  { emoji: "🌳", en: "tree",                         th: "ton mai",                  script: "ต้นไม้",                    cat: "nature" },
  { emoji: "🌸", en: "flower",                       th: "dok mai",                  script: "ดอกไม้",                    cat: "nature" },
  { emoji: "🌿", en: "grass",                        th: "ya",                       script: "หญ้า",                      cat: "nature" },

  // ── Weather (10) ──
  { emoji: "🌡️", en: "hot (weather)",                th: "rorn",                     script: "ร้อน",                      cat: "weather" },
  { emoji: "🥶", en: "cold (weather)",               th: "nao",                      script: "หนาว",                      cat: "weather" },
  { emoji: "😎", en: "cool",                         th: "yen",                      script: "เย็น",                      cat: "weather" },
  { emoji: "🌧️", en: "it's raining",                 th: "fon tok",                  script: "ฝนตก",                      cat: "weather" },
  { emoji: "☀️", en: "sunny",                        th: "daet ork",                 script: "แดดออก",                    cat: "weather" },
  { emoji: "☁️", en: "cloudy",                       th: "fa mit",                   script: "ฟ้ามืด",                    cat: "weather" },
  { emoji: "💨", en: "windy",                        th: "lom paed",                 script: "ลมแรง",                     cat: "weather" },
  { emoji: "💦", en: "humid",                        th: "cheun",                    script: "ชื้น",                      cat: "weather" },
  { emoji: "🏜️", en: "dry season",                   th: "na raeng",                 script: "หน้าแล้ง",                  cat: "weather" },
  { emoji: "🌧️", en: "rainy season",                 th: "na fon",                   script: "หน้าฝน",                    cat: "weather" },

  // ── Places (25) ──
  { emoji: "🏠", en: "house / home",                 th: "ban",                      script: "บ้าน",                      cat: "places" },
  { emoji: "🏨", en: "hotel",                        th: "rong raem",                script: "โรงแรม",                    cat: "places" },
  { emoji: "🏥", en: "hospital",                     th: "rong phayaban",            script: "โรงพยาบาล",                  cat: "places" },
  { emoji: "🏫", en: "school",                       th: "rong rian",                script: "โรงเรียน",                  cat: "places" },
  { emoji: "🎓", en: "university",                   th: "ma-ha-wi-tha-lai",         script: "มหาวิทยาลัย",                cat: "places" },
  { emoji: "🏢", en: "office",                       th: "sam-nak-ngan",             script: "สำนักงาน",                  cat: "places" },
  { emoji: "🏦", en: "bank",                         th: "tha-na-khan",              script: "ธนาคาร",                    cat: "places" },
  { emoji: "📮", en: "post office",                  th: "prai-sa-nee",              script: "ไปรษณีย์",                  cat: "places" },
  { emoji: "👮", en: "police station",               th: "sa-than-ee tam-ruat",      script: "สถานีตำรวจ",                 cat: "places" },
  { emoji: "🛕", en: "temple",                       th: "wat",                      script: "วัด",                       cat: "places" },
  { emoji: "🛒", en: "market",                       th: "ta-lat",                   script: "ตลาด",                      cat: "places" },
  { emoji: "🏪", en: "supermarket",                  th: "su-per-mar-ket",           script: "ซูเปอร์มาร์เก็ต",            cat: "places" },
  { emoji: "🏬", en: "mall / department store",      th: "ha-sang",                  script: "ห้างสรรพสินค้า",             cat: "places" },
  { emoji: "🍽️", en: "restaurant",                   th: "raan a-han",               script: "ร้านอาหาร",                 cat: "places" },
  { emoji: "☕", en: "café",                         th: "raan gafae",               script: "ร้านกาแฟ",                  cat: "places" },
  { emoji: "💊", en: "pharmacy",                     th: "raan khai ya",             script: "ร้านขายยา",                 cat: "places" },
  { emoji: "✈️", en: "airport",                      th: "sa-naam-bin",              script: "สนามบิน",                   cat: "places" },
  { emoji: "🚉", en: "train station",                th: "sa-than-ee rot fai",       script: "สถานีรถไฟ",                 cat: "places" },
  { emoji: "🚌", en: "bus station",                  th: "sa-than-ee rot may",       script: "สถานีรถเมล์",                cat: "places" },
  { emoji: "🌳", en: "park",                         th: "su-uan sa-tha-ra-na",      script: "สวนสาธารณะ",                 cat: "places" },
  { emoji: "🦁", en: "zoo",                          th: "su-uan sat",               script: "สวนสัตว์",                  cat: "places" },
  { emoji: "🏛️", en: "museum",                       th: "phi-phi-ta-phan",          script: "พิพิธภัณฑ์",                 cat: "places" },
  { emoji: "🏛️", en: "embassy",                      th: "sa-than-toot",             script: "สถานทูต",                   cat: "places" },
  { emoji: "🚧", en: "border",                       th: "chai daen",                script: "ชายแดน",                    cat: "places" },
  { emoji: "🏝️", en: "island",                       th: "ko",                       script: "เกาะ",                      cat: "places" },

  // ── Transport (12) ──
  { emoji: "🚗", en: "car",                          th: "rot",                      script: "รถ",                        cat: "transport" },
  { emoji: "🏍️", en: "motorbike",                    th: "rot mor-ter-sai",          script: "รถมอเตอร์ไซค์",              cat: "transport" },
  { emoji: "🚌", en: "bus",                          th: "rot may",                  script: "รถเมล์",                    cat: "transport" },
  { emoji: "🚂", en: "train",                        th: "rot fai",                  script: "รถไฟ",                      cat: "transport" },
  { emoji: "🚕", en: "taxi",                         th: "taxi",                     script: "แท็กซี่",                   cat: "transport" },
  { emoji: "🛺", en: "tuk-tuk",                      th: "tuk-tuk",                  script: "ตุ๊กตุ๊ก",                  cat: "transport" },
  { emoji: "⛵", en: "boat",                         th: "reua",                     script: "เรือ",                      cat: "transport" },
  { emoji: "✈️", en: "plane",                        th: "khreuang bin",             script: "เครื่องบิน",                 cat: "transport" },
  { emoji: "🚲", en: "bicycle",                      th: "rot jak-gra-yaan",         script: "รถจักรยาน",                 cat: "transport" },
  { emoji: "🚇", en: "subway / MRT",                 th: "rot fai tai din",          script: "รถไฟใต้ดิน",                 cat: "transport" },
  { emoji: "🎫", en: "ticket",                       th: "tua",                      script: "ตั๋ว",                      cat: "transport" },
  { emoji: "🛣️", en: "road / street",                th: "thanon",                   script: "ถนน",                       cat: "transport" },

  // ── Home (15) ──
  { emoji: "🚪", en: "room",                         th: "hong",                     script: "ห้อง",                      cat: "home" },
  { emoji: "🛏️", en: "bedroom",                      th: "hong norn",                script: "ห้องนอน",                   cat: "home" },
  { emoji: "🚿", en: "bathroom",                     th: "hong nam",                 script: "ห้องน้ำ",                   cat: "home" },
  { emoji: "🍳", en: "kitchen",                      th: "khrua",                    script: "ครัว",                      cat: "home" },
  { emoji: "🛋️", en: "living room",                  th: "hong nang len",            script: "ห้องนั่งเล่น",               cat: "home" },
  { emoji: "🚪", en: "door",                         th: "pra-too",                  script: "ประตู",                     cat: "home" },
  { emoji: "🪟", en: "window",                       th: "na-tang",                  script: "หน้าต่าง",                  cat: "home" },
  { emoji: "🪑", en: "table",                        th: "toh",                      script: "โต๊ะ",                      cat: "home" },
  { emoji: "🪑", en: "chair",                        th: "gao-ee",                   script: "เก้าอี้",                   cat: "home" },
  { emoji: "🛏️", en: "bed",                          th: "tiang",                    script: "เตียง",                     cat: "home" },
  { emoji: "🛌", en: "pillow",                       th: "morn",                     script: "หมอน",                      cat: "home" },
  { emoji: "❄️", en: "air conditioning",             th: "ea",                       script: "แอร์",                      cat: "home" },
  { emoji: "🌀", en: "fan",                          th: "phat lom",                 script: "พัดลม",                     cat: "home" },
  { emoji: "📺", en: "television",                   th: "tho-ra-that",              script: "โทรทัศน์",                  cat: "home" },
  { emoji: "🧊", en: "refrigerator",                 th: "too yen",                  script: "ตู้เย็น",                   cat: "home" },

  // ── Verbs (80) ──
  { emoji: "🍽️", en: "eat",                          th: "kin",                      script: "กิน",                       cat: "verbs" },
  { emoji: "🥤", en: "drink",                        th: "deum",                     script: "ดื่ม",                      cat: "verbs" },
  { emoji: "😴", en: "sleep",                        th: "norn",                     script: "นอน",                       cat: "verbs" },
  { emoji: "⏰", en: "wake up",                      th: "teun",                     script: "ตื่น",                      cat: "verbs" },
  { emoji: "👉", en: "go",                           th: "pai",                      script: "ไป",                        cat: "verbs" },
  { emoji: "👈", en: "come",                         th: "ma",                       script: "มา",                        cat: "verbs", note: "mid tone; same syllable as dog (falling) and horse (rising)" },
  { emoji: "🙋", en: "want",                         th: "ao / yaak",                script: "เอา / อยาก",                cat: "verbs", note: "ao = colloquial 'want/take'; yaak = to want/wish (more formal)" },
  { emoji: "🙅", en: "don't want",                   th: "mai ao",                   script: "ไม่เอา",                    cat: "verbs" },
  { emoji: "😍", en: "like",                         th: "chob",                     script: "ชอบ",                       cat: "verbs" },
  { emoji: "❤️", en: "love",                         th: "rak",                      script: "รัก",                       cat: "verbs" },
  { emoji: "😠", en: "hate",                         th: "gliat",                    script: "เกลียด",                    cat: "verbs" },
  { emoji: "👁️", en: "see",                          th: "hen",                      script: "เห็น",                      cat: "verbs" },
  { emoji: "👀", en: "look / watch",                 th: "doo",                      script: "ดู",                        cat: "verbs" },
  { emoji: "👂", en: "listen",                       th: "fang",                     script: "ฟัง",                       cat: "verbs" },
  { emoji: "💬", en: "speak / talk",                 th: "poot",                     script: "พูด",                       cat: "verbs" },
  { emoji: "📖", en: "read",                         th: "an",                       script: "อ่าน",                      cat: "verbs" },
  { emoji: "✏️", en: "write",                        th: "khian",                    script: "เขียน",                     cat: "verbs" },
  { emoji: "💡", en: "understand",                   th: "khao jai",                 script: "เข้าใจ",                    cat: "verbs" },
  { emoji: "🧠", en: "know",                         th: "roo",                      script: "รู้",                       cat: "verbs" },
  { emoji: "💭", en: "think",                        th: "khit",                     script: "คิด",                       cat: "verbs" },
  { emoji: "🧠", en: "remember",                     th: "jam",                      script: "จำ",                        cat: "verbs" },
  { emoji: "😶", en: "forget",                       th: "leum",                     script: "ลืม",                       cat: "verbs" },
  { emoji: "🤝", en: "help",                         th: "chuay",                    script: "ช่วย",                      cat: "verbs" },
  { emoji: "🛍️", en: "buy",                          th: "seu",                      script: "ซื้อ",                      cat: "verbs" },
  { emoji: "🏷️", en: "sell",                         th: "khai",                     script: "ขาย",                       cat: "verbs", note: "same romanization as egg (khai, food) — tones differ" },
  { emoji: "💳", en: "pay",                          th: "jai ngoen",                script: "จ่ายเงิน",                  cat: "verbs" },
  { emoji: "✅", en: "have",                         th: "mee",                      script: "มี",                        cat: "verbs" },
  { emoji: "❌", en: "don't have",                   th: "mai mee",                  script: "ไม่มี",                     cat: "verbs" },
  { emoji: "💪", en: "can",                          th: "dai",                      script: "ได้",                       cat: "verbs", note: "also: past tense marker placed after verb; 'to get/obtain'" },
  { emoji: "🚫", en: "cannot",                       th: "mai dai",                  script: "ไม่ได้",                    cat: "verbs", note: "mai = negation; dai = can; mai dai also = 'didn't' (past tense)" },
  { emoji: "🔨", en: "do / make",                    th: "tham",                     script: "ทำ",                        cat: "verbs", note: "also means 'ask' when written differently; context clarifies" },
  { emoji: "🏠", en: "stay / live",                  th: "yoo",                      script: "อยู่",                      cat: "verbs" },
  { emoji: "🪑", en: "sit",                          th: "nang",                     script: "นั่ง",                      cat: "verbs" },
  { emoji: "🧍", en: "stand",                        th: "yeun",                     script: "ยืน",                       cat: "verbs" },
  { emoji: "🚶", en: "walk",                         th: "dern",                     script: "เดิน",                      cat: "verbs" },
  { emoji: "🏃", en: "run",                          th: "wing",                     script: "วิ่ง",                      cat: "verbs" },
  { emoji: "🚗", en: "drive",                        th: "khap",                     script: "ขับ",                       cat: "verbs" },
  { emoji: "🏍️", en: "ride (motorbike)",             th: "khee",                     script: "ขี่",                       cat: "verbs" },
  { emoji: "✈️", en: "fly",                          th: "bin",                      script: "บิน",                       cat: "verbs" },
  { emoji: "🏊", en: "swim",                         th: "way nam",                  script: "ว่ายน้ำ",                   cat: "verbs" },
  { emoji: "👨‍🍳", en: "cook",                        th: "tam khrua",                script: "ทำครัว",                    cat: "verbs" },
  { emoji: "🧹", en: "clean",                        th: "tham kwahm sa-aat",        script: "ทำความสะอาด",                cat: "verbs" },
  { emoji: "🧼", en: "wash",                         th: "lang",                     script: "ล้าง",                      cat: "verbs" },
  { emoji: "🔓", en: "open",                         th: "poet",                     script: "เปิด",                      cat: "verbs" },
  { emoji: "🔒", en: "close",                        th: "pit",                      script: "ปิด",                       cat: "verbs" },
  { emoji: "📞", en: "call (phone)",                 th: "tho",                      script: "โทร",                       cat: "verbs" },
  { emoji: "📤", en: "send",                         th: "song",                     script: "ส่ง",                       cat: "verbs" },
  { emoji: "📥", en: "receive",                      th: "rap",                      script: "รับ",                       cat: "verbs" },
  { emoji: "🔍", en: "find",                         th: "ha",                       script: "หา",                        cat: "verbs" },
  { emoji: "🎁", en: "give",                         th: "hai",                      script: "ให้",                       cat: "verbs" },
  { emoji: "✋", en: "take",                         th: "ao",                       script: "เอา",                       cat: "verbs" },
  { emoji: "🚪", en: "leave / go out",               th: "ork",                      script: "ออก",                       cat: "verbs" },
  { emoji: "📍", en: "arrive",                       th: "theung",                   script: "ถึง",                       cat: "verbs" },
  { emoji: "⏳", en: "wait",                         th: "ror",                      script: "รอ",                        cat: "verbs" },
  { emoji: "🤝", en: "meet",                         th: "phob",                     script: "พบ",                        cat: "verbs" },
  { emoji: "❓", en: "ask",                          th: "tham",                     script: "ถาม",                       cat: "verbs" },
  { emoji: "💬", en: "answer",                       th: "tob",                      script: "ตอบ",                       cat: "verbs" },
  { emoji: "📚", en: "study",                        th: "rian",                     script: "เรียน",                     cat: "verbs" },
  { emoji: "💼", en: "work",                         th: "tham ngan",                script: "ทำงาน",                     cat: "verbs" },
  { emoji: "🎮", en: "play",                         th: "len",                      script: "เล่น",                      cat: "verbs" },
  { emoji: "🎤", en: "sing",                         th: "rong phleng",              script: "ร้องเพลง",                  cat: "verbs" },
  { emoji: "💃", en: "dance",                        th: "ten",                      script: "เต้น",                      cat: "verbs" },
  { emoji: "😂", en: "laugh",                        th: "hua roh",                  script: "หัวเราะ",                   cat: "verbs" },
  { emoji: "😢", en: "cry",                          th: "rong hai",                 script: "ร้องไห้",                   cat: "verbs" },
  { emoji: "😊", en: "smile",                        th: "yim",                      script: "ยิ้ม",                      cat: "verbs" },
  { emoji: "😰", en: "worry",                        th: "pen huang",                script: "เป็นห่วง",                  cat: "verbs" },
  { emoji: "⚡", en: "hurry",                        th: "reo reo",                  script: "เร็วเร็ว",                  cat: "verbs" },
  { emoji: "😌", en: "rest",                         th: "phak",                     script: "พัก",                       cat: "verbs" },
  { emoji: "🏋️", en: "exercise",                     th: "ork gam lang gai",         script: "ออกกำลังกาย",                cat: "verbs" },
  { emoji: "🚿", en: "shower",                       th: "ab nam",                   script: "อาบน้ำ",                    cat: "verbs" },
  { emoji: "↩️", en: "return",                       th: "glap",                     script: "กลับ",                      cat: "verbs" },
  { emoji: "📚", en: "borrow",                       th: "yaem",                     script: "ยืม",                       cat: "verbs" },
  { emoji: "🧪", en: "try",                          th: "long / pha-ya-yam",        script: "ลอง / พยายาม",              cat: "verbs" },
  { emoji: "🔍", en: "check",                        th: "truat sob",                script: "ตรวจสอบ",                   cat: "verbs" },
  { emoji: "🔄", en: "change",                       th: "plian",                    script: "เปลี่ยน",                   cat: "verbs" },
  { emoji: "☑️", en: "choose",                       th: "leuak",                    script: "เลือก",                     cat: "verbs" },
  { emoji: "🔧", en: "use",                          th: "chai",                     script: "ใช้",                       cat: "verbs" },
  { emoji: "▶️", en: "start",                        th: "rerm",                     script: "เริ่ม",                     cat: "verbs" },
  { emoji: "✅", en: "finish",                       th: "set",                      script: "เสร็จ",                     cat: "verbs" },
  { emoji: "😞", en: "lose",                         th: "hai",                      script: "หาย",                       cat: "verbs" },

  // ── Adjectives (55) ──
  { emoji: "👍", en: "good",                         th: "dee",                      script: "ดี",                        cat: "adjectives" },
  { emoji: "👎", en: "bad",                          th: "mai dee / chua",           script: "ไม่ดี / ชั่ว",              cat: "adjectives" },
  { emoji: "😍", en: "beautiful",                    th: "suai",                     script: "สวย",                       cat: "adjectives" },
  { emoji: "🥰", en: "cute",                         th: "narak",                    script: "น่ารัก",                    cat: "adjectives" },
  { emoji: "🔍", en: "big",                          th: "yai",                      script: "ใหญ่",                      cat: "adjectives" },
  { emoji: "🔬", en: "small",                        th: "lek",                      script: "เล็ก",                      cat: "adjectives" },
  { emoji: "📏", en: "tall",                         th: "soong",                    script: "สูง",                       cat: "adjectives" },
  { emoji: "🦔", en: "short (height)",               th: "tia",                      script: "เตี้ย",                     cat: "adjectives" },
  { emoji: "📐", en: "long",                         th: "yao",                      script: "ยาว",                       cat: "adjectives" },
  { emoji: "✂️", en: "short (length)",               th: "san",                      script: "สั้น",                      cat: "adjectives" },
  { emoji: "↔️", en: "wide",                         th: "gwang",                    script: "กว้าง",                     cat: "adjectives" },
  { emoji: "↕️", en: "narrow",                       th: "kaep",                     script: "แคบ",                       cat: "adjectives" },
  { emoji: "🏋️", en: "heavy",                        th: "nak",                      script: "หนัก",                      cat: "adjectives" },
  { emoji: "🪶", en: "light (weight)",               th: "bow",                      script: "เบา",                       cat: "adjectives" },
  { emoji: "🔥", en: "hot",                          th: "rorn",                     script: "ร้อน",                      cat: "adjectives" },
  { emoji: "🥶", en: "cold",                         th: "yen",                      script: "เย็น",                      cat: "adjectives" },
  { emoji: "🌡️", en: "warm",                         th: "oon",                      script: "อุ่น",                      cat: "adjectives" },
  { emoji: "⚡", en: "fast",                         th: "reo",                      script: "เร็ว",                      cat: "adjectives" },
  { emoji: "🐢", en: "slow",                         th: "cha",                      script: "ช้า",                       cat: "adjectives" },
  { emoji: "😌", en: "easy",                         th: "ngai",                     script: "ง่าย",                      cat: "adjectives" },
  { emoji: "😤", en: "difficult",                    th: "yaak",                     script: "ยาก",                       cat: "adjectives" },
  { emoji: "🎉", en: "fun",                          th: "sanook",                   script: "สนุก",                      cat: "adjectives" },
  { emoji: "😴", en: "boring",                       th: "na beua",                  script: "น่าเบื่อ",                  cat: "adjectives" },
  { emoji: "🤩", en: "interesting",                  th: "na son jai",               script: "น่าสนใจ",                   cat: "adjectives" },
  { emoji: "😩", en: "tired",                        th: "neuy",                     script: "เหนื่อย",                   cat: "adjectives" },
  { emoji: "🍽️", en: "hungry",                       th: "hiu",                      script: "หิว",                       cat: "adjectives" },
  { emoji: "💧", en: "thirsty",                      th: "hiu nam",                  script: "หิวน้ำ",                    cat: "adjectives" },
  { emoji: "😋", en: "full (after eating)",          th: "im",                       script: "อิ่ม",                      cat: "adjectives" },
  { emoji: "😊", en: "happy",                        th: "dee jai",                  script: "ดีใจ",                      cat: "adjectives" },
  { emoji: "😢", en: "sad",                          th: "sia jai",                  script: "เสียใจ",                    cat: "adjectives" },
  { emoji: "😠", en: "angry",                        th: "grot",                     script: "โกรธ",                      cat: "adjectives" },
  { emoji: "😨", en: "scared",                       th: "glua",                     script: "กลัว",                      cat: "adjectives" },
  { emoji: "🤩", en: "excited",                      th: "teun ten",                 script: "ตื่นเต้น",                  cat: "adjectives" },
  { emoji: "💰", en: "expensive",                    th: "phaeng",                   script: "แพง",                       cat: "adjectives" },
  { emoji: "🏷️", en: "cheap",                        th: "thook",                    script: "ถูก",                       cat: "adjectives" },
  { emoji: "📍", en: "near",                         th: "klai",                     script: "ใกล้",                      cat: "adjectives" },
  { emoji: "🗺️", en: "far",                          th: "glai",                     script: "ไกล",                       cat: "adjectives" },
  { emoji: "✨", en: "new",                          th: "mai",                      script: "ใหม่",                      cat: "adjectives" },
  { emoji: "🕰️", en: "old",                          th: "gao",                      script: "เก่า",                      cat: "adjectives" },
  { emoji: "✨", en: "clean",                        th: "sa-aat",                   script: "สะอาด",                     cat: "adjectives" },
  { emoji: "🗑️", en: "dirty",                        th: "sok-ga-prok",              script: "สกปรก",                     cat: "adjectives" },
  { emoji: "🤫", en: "quiet",                        th: "ngiap",                    script: "เงียบ",                     cat: "adjectives" },
  { emoji: "📢", en: "noisy",                        th: "dang",                     script: "ดัง",                       cat: "adjectives" },
  { emoji: "🛡️", en: "safe",                         th: "phlot-pai",                script: "ปลอดภัย",                   cat: "adjectives" },
  { emoji: "⚠️", en: "dangerous",                    th: "an-ta-rai",                script: "อันตราย",                   cat: "adjectives" },
  { emoji: "✅", en: "correct",                      th: "thook-tong",               script: "ถูกต้อง",                   cat: "adjectives" },
  { emoji: "❌", en: "wrong",                        th: "phit",                     script: "ผิด",                       cat: "adjectives" },
  { emoji: "🟰", en: "same",                         th: "meuan",                    script: "เหมือน",                    cat: "adjectives" },
  { emoji: "🔀", en: "different",                    th: "tang",                     script: "ต่าง",                      cat: "adjectives" },
  { emoji: "⚖️", en: "enough",                       th: "por",                      script: "พอ",                        cat: "adjectives" },
  { emoji: "➕", en: "more",                         th: "ik",                       script: "อีก",                       cat: "adjectives" },
  { emoji: "➖", en: "less",                         th: "noi long",                 script: "น้อยลง",                    cat: "adjectives" },
  { emoji: "💯", en: "a lot / very",                 th: "mak",                      script: "มาก",                       cat: "adjectives" },
  { emoji: "🤏", en: "a little",                     th: "nit noy",                  script: "นิดหน่อย",                  cat: "adjectives" },
  { emoji: "🔋", en: "full (not empty)",             th: "tem",                      script: "เต็ม",                      cat: "adjectives" },

  // ── Time (25) ──
  { emoji: "⏱️", en: "now",                          th: "tawn nee",                 script: "ตอนนี้",                    cat: "time" },
  { emoji: "📅", en: "today",                        th: "wan nee",                  script: "วันนี้",                    cat: "time" },
  { emoji: "🌅", en: "tomorrow",                     th: "prung nee",                script: "พรุ่งนี้",                  cat: "time" },
  { emoji: "⏪", en: "yesterday",                    th: "meua wan",                 script: "เมื่อวาน",                  cat: "time" },
  { emoji: "📅", en: "day after tomorrow",           th: "ma-reun nee",              script: "มะรืนนี้",                  cat: "time" },
  { emoji: "🌄", en: "morning",                      th: "torn chao",                script: "ตอนเช้า",                   cat: "time" },
  { emoji: "☀️", en: "afternoon",                    th: "torn bai",                 script: "ตอนบ่าย",                   cat: "time" },
  { emoji: "🌆", en: "evening",                      th: "torn yen",                 script: "ตอนเย็น",                   cat: "time" },
  { emoji: "🌙", en: "night",                        th: "torn keun",                script: "ตอนคืน",                    cat: "time" },
  { emoji: "🌃", en: "midnight",                     th: "thiang keun",              script: "เที่ยงคืน",                 cat: "time" },
  { emoji: "📆", en: "day",                          th: "wan",                      script: "วัน",                       cat: "time" },
  { emoji: "📅", en: "week",                         th: "a-thit",                   script: "อาทิตย์",                   cat: "time" },
  { emoji: "🗓️", en: "month",                        th: "deuan",                    script: "เดือน",                     cat: "time" },
  { emoji: "🎊", en: "year",                         th: "pee",                      script: "ปี",                        cat: "time" },
  { emoji: "⏰", en: "hour",                         th: "chua mong",                script: "ชั่วโมง",                   cat: "time" },
  { emoji: "⏱️", en: "minute",                       th: "na-thee",                  script: "นาที",                      cat: "time" },
  { emoji: "🐓", en: "early",                        th: "raeo",                     script: "เร็ว",                      cat: "time" },
  { emoji: "🕰️", en: "late",                         th: "sai",                      script: "สาย",                       cat: "time" },
  { emoji: "✅", en: "on time",                      th: "trong way-la",             script: "ตรงเวลา",                   cat: "time" },
  { emoji: "🔁", en: "always",                       th: "sa-mer",                   script: "เสมอ",                      cat: "time" },
  { emoji: "🔂", en: "sometimes",                    th: "bang krang",               script: "บางครั้ง",                  cat: "time" },
  { emoji: "🚫", en: "never",                        th: "mai koey",                 script: "ไม่เคย",                    cat: "time" },
  { emoji: "✅", en: "already",                      th: "laew",                     script: "แล้ว",                      cat: "time" },
  { emoji: "⏳", en: "not yet",                      th: "yang mai",                 script: "ยังไม่",                    cat: "time" },
  { emoji: "⏩", en: "soon",                         th: "ik diaw",                  script: "อีกเดี๋ยว",                 cat: "time" },

  // ── Days (7) ──
  { emoji: "📅", en: "Monday",                       th: "wan jan",                  script: "วันจันทร์",                 cat: "days" },
  { emoji: "📅", en: "Tuesday",                      th: "wan ang-khan",             script: "วันอังคาร",                 cat: "days" },
  { emoji: "📅", en: "Wednesday",                    th: "wan phut",                 script: "วันพุธ",                    cat: "days" },
  { emoji: "📅", en: "Thursday",                     th: "wan pha-rue-hat",          script: "วันพฤหัสบดี",               cat: "days" },
  { emoji: "📅", en: "Friday",                       th: "wan suk",                  script: "วันศุกร์",                  cat: "days" },
  { emoji: "📅", en: "Saturday",                     th: "wan sao",                  script: "วันเสาร์",                  cat: "days" },
  { emoji: "📅", en: "Sunday",                       th: "wan a-thit",               script: "วันอาทิตย์",                cat: "days" },

  // ── Months (12) ──
  { emoji: "🗓️", en: "January",                      th: "ma-ga-ra-khom",            script: "มกราคม",                    cat: "months" },
  { emoji: "🗓️", en: "February",                     th: "gum-pha-phan",             script: "กุมภาพันธ์",                 cat: "months" },
  { emoji: "🗓️", en: "March",                        th: "mee-na-khom",              script: "มีนาคม",                    cat: "months" },
  { emoji: "🗓️", en: "April",                        th: "may-sa-yon",               script: "เมษายน",                    cat: "months" },
  { emoji: "🗓️", en: "May",                          th: "phreut-sa-pha-khom",       script: "พฤษภาคม",                   cat: "months" },
  { emoji: "🗓️", en: "June",                         th: "mi-thu-na-yon",            script: "มิถุนายน",                  cat: "months" },
  { emoji: "🗓️", en: "July",                         th: "ga-ra-ga-da-khom",         script: "กรกฎาคม",                   cat: "months" },
  { emoji: "🗓️", en: "August",                       th: "sing-ha-khom",             script: "สิงหาคม",                   cat: "months" },
  { emoji: "🗓️", en: "September",                    th: "gan-ya-yon",               script: "กันยายน",                   cat: "months" },
  { emoji: "🗓️", en: "October",                      th: "tu-la-khom",               script: "ตุลาคม",                    cat: "months" },
  { emoji: "🗓️", en: "November",                     th: "phreut-sa-ji-ga-yon",      script: "พฤศจิกายน",                 cat: "months" },
  { emoji: "🗓️", en: "December",                     th: "than-wa-khom",             script: "ธันวาคม",                   cat: "months" },

  // ── Directions (10) ──
  { emoji: "⬅️", en: "left",                         th: "sai",                      script: "ซ้าย",                      cat: "directions" },
  { emoji: "➡️", en: "right",                        th: "khwa",                     script: "ขวา",                       cat: "directions" },
  { emoji: "⬆️", en: "straight ahead",               th: "trong pai",                script: "ตรงไป",                     cat: "directions" },
  { emoji: "↩️", en: "turn",                         th: "leo",                      script: "เลี้ยว",                    cat: "directions" },
  { emoji: "🧭", en: "north",                        th: "nuea",                     script: "เหนือ",                     cat: "directions" },
  { emoji: "🧭", en: "south",                        th: "tai",                      script: "ใต้",                       cat: "directions" },
  { emoji: "🧭", en: "east",                         th: "tawan ork",                script: "ตะวันออก",                  cat: "directions" },
  { emoji: "🧭", en: "west",                         th: "tawan tok",                script: "ตะวันตก",                   cat: "directions" },
  { emoji: "📍", en: "near",                         th: "klai",                     script: "ใกล้",                      cat: "directions" },
  { emoji: "🗺️", en: "far",                          th: "glai",                     script: "ไกล",                       cat: "directions" },

  // ── Shopping (12) ──
  { emoji: "💰", en: "money",                        th: "ngoen",                    script: "เงิน",                      cat: "shopping" },
  { emoji: "💵", en: "baht (currency)",              th: "baht",                     script: "บาท",                       cat: "shopping" },
  { emoji: "🏷️", en: "how much?",                    th: "tao rai",                  script: "เท่าไร",                    cat: "shopping" },
  { emoji: "📉", en: "discount",                     th: "lot ra ka",                script: "ลดราคา",                    cat: "shopping" },
  { emoji: "🧾", en: "receipt",                      th: "bai set",                  script: "ใบเสร็จ",                   cat: "shopping" },
  { emoji: "💵", en: "cash",                         th: "ngoen sot",                script: "เงินสด",                    cat: "shopping" },
  { emoji: "💳", en: "credit card",                  th: "bat kre-dit",              script: "บัตรเครดิต",                 cat: "shopping" },
  { emoji: "🆓", en: "free (no cost)",               th: "free",                     script: "ฟรี",                       cat: "shopping" },
  { emoji: "📐", en: "size",                         th: "kha-nat",                  script: "ขนาด",                      cat: "shopping" },
  { emoji: "🏷️", en: "price",                        th: "ra-kha",                   script: "ราคา",                      cat: "shopping" },
  { emoji: "🛍️", en: "bag (shopping)",               th: "thong",                    script: "ถุง",                       cat: "shopping" },
  { emoji: "🪙", en: "change (coins)",               th: "ngoen torn",               script: "เงินทอน",                   cat: "shopping" },

  // ── Health (20) ──
  { emoji: "👨‍⚕️", en: "doctor",                       th: "moh",                      script: "หมอ",                       cat: "health" },
  { emoji: "👩‍⚕️", en: "nurse",                        th: "pha-ya-ban",               script: "พยาบาล",                    cat: "health" },
  { emoji: "💊", en: "medicine",                     th: "ya",                       script: "ยา",                        cat: "health" },
  { emoji: "🤒", en: "sick / unwell",                th: "mai sa-bai",               script: "ไม่สบาย",                   cat: "health" },
  { emoji: "🤕", en: "hurt / pain",                  th: "jep",                      script: "เจ็บ",                      cat: "health" },
  { emoji: "🤯", en: "headache",                     th: "puad hua",                 script: "ปวดหัว",                    cat: "health" },
  { emoji: "🫃", en: "stomach ache",                 th: "puad thong",               script: "ปวดท้อง",                   cat: "health" },
  { emoji: "🌡️", en: "fever",                        th: "pen khai",                 script: "เป็นไข้",                   cat: "health" },
  { emoji: "🤧", en: "cold (illness)",               th: "pen wat",                  script: "เป็นหวัด",                  cat: "health" },
  { emoji: "😮", en: "cough",                        th: "ai",                       script: "ไอ",                        cat: "health" },
  { emoji: "🤧", en: "allergy",                      th: "phaeng",                   script: "แพ้",                       cat: "health" },
  { emoji: "🚨", en: "emergency",                    th: "chuak-chern",              script: "ฉุกเฉิน",                   cat: "health" },
  { emoji: "🚑", en: "ambulance",                    th: "rot pha-ya-ban",           script: "รถพยาบาล",                  cat: "health" },
  { emoji: "🩸", en: "blood",                        th: "leuad",                    script: "เลือด",                     cat: "health" },
  { emoji: "💫", en: "dizzy",                        th: "wian hua",                 script: "เวียนหัว",                  cat: "health" },
  { emoji: "🤒", en: "I feel unwell",                th: "phom mai sa-bai",          script: "ผมไม่สบาย",                 cat: "health" },
  { emoji: "📞", en: "call a doctor",                th: "riak moh",                 script: "เรียกหมอ",                  cat: "health" },
  { emoji: "💊", en: "pharmacy",                     th: "raan khai ya",             script: "ร้านขายยา",                 cat: "health" },
  { emoji: "😩", en: "tired / exhausted",            th: "neuy",                     script: "เหนื่อย",                   cat: "health" },
  { emoji: "🩹", en: "broken / injured",             th: "hak / bat jep",           script: "หัก / บาดเจ็บ",             cat: "health" },

  // ── Emotions (15) ──
  { emoji: "😄", en: "happy",                        th: "dee jai",                  script: "ดีใจ",                      cat: "emotions" },
  { emoji: "😢", en: "sad",                          th: "sia jai",                  script: "เสียใจ",                    cat: "emotions" },
  { emoji: "😡", en: "angry",                        th: "grot",                     script: "โกรธ",                      cat: "emotions" },
  { emoji: "😱", en: "scared",                       th: "glua",                     script: "กลัว",                      cat: "emotions" },
  { emoji: "😔", en: "lonely",                       th: "ngao",                     script: "เหงา",                      cat: "emotions" },
  { emoji: "😰", en: "stressed",                     th: "khriat",                   script: "เครียด",                    cat: "emotions" },
  { emoji: "😌", en: "relaxed",                      th: "sa-bai jai",               script: "สบายใจ",                    cat: "emotions" },
  { emoji: "🦁", en: "proud",                        th: "pa-oom jai",               script: "ภูมิใจ",                    cat: "emotions" },
  { emoji: "😳", en: "embarrassed",                  th: "a-y",                      script: "อาย",                       cat: "emotions" },
  { emoji: "😒", en: "jealous",                      th: "it-cha",                   script: "อิจฉา",                     cat: "emotions" },
  { emoji: "😵", en: "confused",                     th: "ngong",                    script: "งง",                        cat: "emotions" },
  { emoji: "🤩", en: "excited",                      th: "teun ten",                 script: "ตื่นเต้น",                  cat: "emotions" },
  { emoji: "😬", en: "nervous",                      th: "neua non mai yu",          script: "เนื้อนอนไม่หลับ",            cat: "emotions" },
  { emoji: "🙏", en: "grateful",                     th: "kob jai",                  script: "ขอบใจ",                     cat: "emotions" },
  { emoji: "😒", en: "bored",                        th: "beua",                     script: "เบื่อ",                     cat: "emotions" },

  // ── Work & school (20) ──
  { emoji: "💼", en: "work",                         th: "tham ngan",                script: "ทำงาน",                     cat: "work" },
  { emoji: "👷", en: "job / career",                 th: "a-cheep",                  script: "อาชีพ",                     cat: "work" },
  { emoji: "👔", en: "boss",                         th: "jao nai",                  script: "เจ้านาย",                   cat: "work" },
  { emoji: "🤝", en: "colleague",                    th: "pheuan ruam ngan",         script: "เพื่อนร่วมงาน",              cat: "work" },
  { emoji: "📊", en: "meeting",                      th: "pra-chum",                 script: "ประชุม",                    cat: "work" },
  { emoji: "💻", en: "computer",                     th: "khom-phiu-ter",            script: "คอมพิวเตอร์",               cat: "work" },
  { emoji: "📱", en: "phone",                        th: "tho-ra-sap",               script: "โทรศัพท์",                  cat: "work" },
  { emoji: "📧", en: "email",                        th: "ee-mel",                   script: "อีเมล",                     cat: "work" },
  { emoji: "🏫", en: "school",                       th: "rong rian",                script: "โรงเรียน",                  cat: "work" },
  { emoji: "👩‍🏫", en: "teacher",                      th: "khruu",                    script: "ครู",                       cat: "work" },
  { emoji: "🧑‍🎓", en: "student",                      th: "nak rian",                 script: "นักเรียน",                  cat: "work" },
  { emoji: "📝", en: "homework",                     th: "gan ban",                  script: "การบ้าน",                   cat: "work" },
  { emoji: "📋", en: "exam / test",                  th: "sob",                      script: "สอบ",                       cat: "work" },
  { emoji: "✅", en: "pass",                         th: "phan",                     script: "ผ่าน",                      cat: "work" },
  { emoji: "❌", en: "fail",                         th: "tok",                      script: "ตก",                        cat: "work" },
  { emoji: "💰", en: "salary",                       th: "ngoen deuan",              script: "เงินเดือน",                 cat: "work" },
  { emoji: "🏖️", en: "holiday / day off",            th: "wan yut",                  script: "วันหยุด",                   cat: "work" },
  { emoji: "😵", en: "busy",                         th: "yung",                     script: "ยุ่ง",                      cat: "work" },
  { emoji: "🛋️", en: "free (not busy)",              th: "wang",                     script: "ว่าง",                      cat: "work" },
  { emoji: "📋", en: "project",                      th: "krong-gaan",               script: "โครงการ",                   cat: "work" },
];
